import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import {Button} from '@material-ui/core'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Books Library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <h1>Hello Learners!</h1>
          <Link href='/Books' >
             <Button variant='outlined' >Open Library</Button>
            </Link>
      </main>
    </div>
  )
}
