import { useRouter } from 'next/dist/client/router'
import Head from 'next/head'
import { useEffect, useState } from 'react';
import { getBooks } from '../../utils/getBooks';

export default function Book() {
    const {query} = useRouter();
    const {id} = query;

    const [Book, setBook] = useState({});
    useEffect(() => {
     const book = getBooks(id);
     setBook(book);
    }, [])
  return (
    <div >
      <Head>
        <title>Book Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
          <h1>Book {id} Page</h1>
      </main>
    </div>
  )
}
